### ISSUE TITLE
tanukisoftware wrapper unable to start when using glow root

### ISSUE THREAD

**Issue by goldentigerindia** [glowroot/glowroot#201]
Hi,

We are using tanukisoftware wrapper when starting our Jboss 7.1 based apps. It give the following exception when trying to start with glow root. When we look at  the glow root log(where the glowroot jar file is placed) it says launched successfully. We use JDK 1.7.

STATUS | wrapper  | 2017/04/23 22:30:26 | Launching a JVM...
INFO   | jvm 1    | 2017/04/23 22:30:26 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/04/23 22:30:26 | WrapperSimpleApp Error: Unable to locate the class org.jboss.modules.Main : java.lang.ClassNotFoundException: org.jboss.modules.Main
INFO   | jvm 1    | 2017/04/23 22:30:26 |
INFO   | jvm 1    | 2017/04/23 22:30:26 | WrapperSimpleApp Usage:
INFO   | jvm 1    | 2017/04/23 22:30:26 |   java org.tanukisoftware.wrapper.WrapperSimpleApp {app_class{/app_method}} [app_arguments]
INFO   | jvm 1    | 2017/04/23 22:30:26 |
INFO   | jvm 1    | 2017/04/23 22:30:26 | Where:
INFO   | jvm 1    | 2017/04/23 22:30:26 |   app_class:      The fully qualified class name of the application to run.
INFO   | jvm 1    | 2017/04/23 22:30:26 |   app_arguments:  The arguments that would normally be passed to the
INFO   | jvm 1    | 2017/04/23 22:30:26 |                   application.
ERROR  | wrapper  | 2017/04/23 22:30:28 | JVM exited while loading the application.
STATUS | wrapper  | 2017/04/23 22:30:32 | Launching a JVM...
INFO   | jvm 2    | 2017/04/23 22:30:33 | WrapperManager: Initializing...
INFO   | jvm 2    | 2017/04/23 22:30:33 | WrapperSimpleApp Error: Unable to locate the class org.jboss.modules.Main : java.lang.ClassNotFoundException: org.jboss.modules.Main
INFO   | jvm 2    | 2017/04/23 22:30:33 |
INFO   | jvm 2    | 2017/04/23 22:30:33 | WrapperSimpleApp Usage:
INFO   | jvm 2    | 2017/04/23 22:30:33 |   java org.tanukisoftware.wrapper.WrapperSimpleApp {app_class{/app_method}} [app_arguments]
INFO   | jvm 2    | 2017/04/23 22:30:33 |
INFO   | jvm 2    | 2017/04/23 22:30:33 | Where:
INFO   | jvm 2    | 2017/04/23 22:30:33 |   app_class:      The fully qualified class name of the application to run.
INFO   | jvm 2    | 2017/04/23 22:30:33 |   app_arguments:  The arguments that would normally be passed to the
INFO   | jvm 2    | 2017/04/23 22:30:33 |                   application.
ERROR  | wrapper  | 2017/04/23 22:30:35 | JVM exited while loading the application.

Thanks,

-Geeth

**Comment by trask** [comment]
Thanks for posting!  Glowroot was not correctly detecting JBoss due to the service wrapper.  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.16-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.16-SNAPSHOT).

You may also have an error in your service wrapper `wrapper.conf`, because I got a different error when I ran it (before fixing glowroot).

If you still have issue, please post your `wrapper.conf` file.

Thanks,
Trask

**Comment by goldentigerindia** [comment]
Thanks a lot Trask. I will try out the new jar and update you. Thanks a lot for getting itdone quickly. Meanwhile I will also start learning the code so that i can also take some bugs and fix it.

I have one question regarding the clustered central collector. I tried setting it up i cant get the jvm features enabled in the ui when my request goes to a host in the cluster that is not connected to the agent that i am looking for . All these features get enabled if luckily the request goes top the cluster machine to which the agent is attached, any workaround to resolve it.

**Comment by trask** [comment]
Can you open an issue for your clustered central collector question and post the glowroot central log files from both nodes?

**Comment by goldentigerindia** [comment]
Sure will open a issue for the clustered central collector. I have to setup cluster again as i had deleted it form cloud since it was not working.
I tested the wrapper fix.I am still facing the issue.


[wrapper.txt](https://github.com/glowroot/glowroot/files/954507/wrapper.txt)
attached is the wrapper.conf. And the log is give below.
[stdout.txt](https://github.com/glowroot/glowroot/files/954526/stdout.txt)

**Comment by trask** [comment]
Hi @goldentigerindia, my guess on your clustered central collector issue, is that if you were using the documented setup:

```
jgroups.configurationFile=default-jgroups-udp.xml
jgroups.udp.mcast_addr=228.6.7.8
jgroups.udp.mcast_port=46655
```

then the nodes try to find each other over UDP/multicast, which may be blocked in your environment, and so you weren't getting the clustered behavior (which includes handing off those JVM features to the central collector that the requested agent is connected to).

I just added a jgroups TCP configuration in the latest snapshot release [glowroot-central-0.9.16-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.9.16-SNAPSHOT). This requires explicitly listing the central collector host names, but is a good option in some cases.

If you are running 2 nodes, `glowroot-1` and `glowroot-2`, you would configure jgroups over tcp in the `glowroot-central.properties` like this:

```
jgroups.configurationFile=default-jgroups-tcp.xml
jgroups.tcp.address=match-host:glowroot-1|glowroot-2
jgroups.tcp.port=7800
jgroups.tcp.initial_hosts=glowroot-1[7800],glowroot-2[7800]
```

To verify that the central collector nodes are finding each other over jgroups, check the central collector log files.

If both nodes are stopped, and you start `glowroot-1` first, you should see something like this in the `glowroot-1` log file:


```
2017-04-27 01:47:10.397 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000094: Received new
cluster view for channel ISPN: [glowroot-1-19045|0] (1) [glowroot-1-19045]
```

Then when you start `glowroot-2`, you should see something like this in both the `glowroot-1` and `glowroot-2` log files:

```
2017-04-27 01:48:11.018 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000094: Received new
cluster view for channel ISPN: [glowroot-1-19045|1] (2) [glowroot-1-19045, glowroot-2-64638]
```

**Comment by goldentigerindia** [comment]
Thanks trask will try .I see someone else also faced same issue and was able to bring it up with your steps.
